# Site Settings
title: Bhavya Sanchaniya | Resume 
url: 'http://bhavyagajjar.freeiz.com'
baseurl: '/resume' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Bhavya Sanchaniya
tagline: Senior Full Stack Web Developer
pic: bhavyasanchaniya.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Senior Full Stack Developer at Company A with 5 years of experience in web development. Specialized in development with Vuejs,Reactjs and Nodejs. Proven ability in data analysis and creating insightful visualization'

#sidebar links
email: bhavyasanchaniya@gmail.com
phone: +91 781 884 1833
website: bhavyagajjar.freeiz.com #do not add http://
linkedin: bhavyasanchaniya
github: bhavyasanchaniya
twitter: '@bhavya_gajjar'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
